### ISSUE TITLE
Wireguard tunnel config issue

### ISSUE THREAD

**Issue by PavelGo3110** [egor-tensin/setup-wireguard#6]
Hi Erog, thanks for the flow.
Can you please clarify how the tunnel interface should look?
It does not recognize the format you shared on the flow

![image](https://user-images.githubusercontent.com/94613985/177821649-66ae8734-ff78-4d82-b4dc-e9e0ea284355.png)

**Comment by PavelGo3110** [comment]
@egor-tensin Also, is it suits windows hoster-runner?

**Comment by egor-tensin** [comment]
Sorry, I was in no fit state to deal with my GitHub Actions for the past year. I'll try to keep up in the future.

Replying just for the sake of completeness, even though this is obviously no longer relevant for you. I think there' s a mistake in your config, which can be fixed by changing "endpoint" to "Endpoint".
